create table chaos_command (
  command_id uuid not null primary key,
  target_application varchar(255) not null,
  action varchar(40) not null,
  environment varchar(40) not null,
  issued_by varchar(255) not null,
  correlation_id varchar(255),
  expires_at timestamp,
  published_at timestamp not null,
  expected_instances integer not null,
  instance_selection varchar(10) not null,
  instance_ids varchar(4000),
  assault varchar(8000)
);

create index idx_chaos_command_app_published
  on chaos_command (target_application, published_at desc);

create table chaos_command_instance_result (
  id bigint generated by default as identity primary key,
  command_id uuid not null,
  instance_id varchar(255) not null,
  outcome varchar(40) not null,
  reported_at timestamp not null,
  failed_step varchar(255),
  http_status integer,
  constraint fk_chaos_result_command
    foreign key (command_id) references chaos_command (command_id),
  constraint uk_chaos_result_instance unique (command_id, instance_id)
);
